### ISSUE TITLE
i need some help: TypeError: Cannot create property 'min' on number '11100'

### ISSUE THREAD

**Issue by laihuyha** [space-commits/SPT-Realism-Mod-Client#44]
┌─────────────────────────────────────┐
│ SPT-AKI 3.8.0                       │
│ https://discord.sp-tarkov.com       │
│                                     │
│ This work is free of charge         │
│ If you paid money, you were scammed │
│ Commercial use is prohibited        │
└─────────────────────────────────────┘
ModLoader: loading 6 server mods...
Mod Faupi-HideoutArchitect is not compatible with the current version of AKI. You may encounter issues - no support will be provided!
Mod: SVM version: 1.8.1 by: GhostFenixx loaded
Mod: SPT Realism Mod version: 1.0.1 by: Fontaine loaded
Mod: Hephaestus version: 1.1.4 by: alexkarpen loaded
Mod: HideoutArchitect version: 1.7.1 by: Faupi loaded
Mod: NoDiscardLimit version: 1.4.0 by: Skwizzy loaded
Mod: SAIN version: 2.1.12 by: zSolarint loaded
Realism: SAIN Detected, Making Adjustments
Server: executing startup callbacks...
Importing database...
Database import finished
SVM 1.8.1 has initialized, Hello, how's your day? :]
SVM Preset - Mahesvara's Personal - successfully loaded
```
**TypeError: Cannot create property 'min' on number '11100'
TypeError: Cannot create property 'min' on number '11100'
    at Traders.loadTraderRefreshTimes (E:\Games\Escape From Tarkov v0.14.1.2.29197\user\mods\SPT-Realism\src\traders\traders.ts:129:59)
    at Main.postDBLoad (E:\Games\Escape From Tarkov v0.14.1.2.29197\user\mods\SPT-Realism\src\mod.ts:733:17)
    at PostDBModLoader.executeMods (C:\snapshot\src\loaders\PostDBModLoader.ts:72:45)
    at PostDBModLoader.onLoad (C:\snapshot\src\loaders\PostDBModLoader.ts:26:24)
    at App.load (C:\snapshot\src\utils\App.ts:56:26)
TypeError: Cannot create property 'min' on number '11100'
TypeError: Cannot create property 'min' on number '11100'
    at Traders.loadTraderRefreshTimes (E:\Games\Escape From Tarkov v0.14.1.2.29197\user\mods\SPT-Realism\src\traders\traders.ts:129:59)
    at Main.postDBLoad (E:\Games\Escape From Tarkov v0.14.1.2.29197\user\mods\SPT-Realism\src\mod.ts:733:17)
    at PostDBModLoader.executeMods (C:\snapshot\src\loaders\PostDBModLoader.ts:72:45)
    at PostDBModLoader.onLoad (C:\snapshot\src\loaders\PostDBModLoader.ts:26:24)
    at App.load (C:\snapshot\src\utils\App.ts:56:26)**
```

**Comment by laihuyha** [comment]
This is an error on the Server mod, not Client, sorry about posting in a wrong place
