### ISSUE TITLE
Cannot read properties of undefined (reading 'TradersInfo')

### ISSUE THREAD

**Issue by facusantillo** [space-commits/SPT-Realism-Mod-Client#71]
Every now and then when openning the server and playing a while, this error pops.

Here is the log:

Cannot read properties of undefined (reading 'TradersInfo')
TypeError: Cannot read properties of undefined (reading 'TradersInfo')
    at C:\Battlestate Games\SPT-3.8.3\user\mods\SPT-Realism\src\traders\traders.ts:460:32
    at Array.forEach (<anonymous>)
    at RandomizeTraderAssort.getAverageLL (C:\Battlestate Games\SPT-3.8.3\user\mods\SPT-Realism\src\traders\traders.ts:458:17)
    at TraderRefresh.modifyTraderAssorts (C:\Battlestate Games\SPT-3.8.3\user\mods\SPT-Realism\src\traders\traders.ts:834:41)
    at TraderRefresh.myResetExpiredTrader (C:\Battlestate Games\SPT-3.8.3\user\mods\SPT-Realism\src\traders\traders.ts:814:40)
    at TraderAssortHelper.resetExpiredTrader (C:\Battlestate Games\SPT-3.8.3\user\mods\SPT-Realism\src\mod.ts:184:38)
    at TraderController.update (C:\snapshot\src\controllers\TraderController.ts:114:41)
    at TraderCallbacks.onUpdate (C:\snapshot\src\callbacks\TraderCallbacks.ts:26:38)
    at App.update (C:\snapshot\src\utils\App.ts:82:44)

As a result, the items in traders are not loading:

![1Gs2I0z](https://github.com/space-commits/SPT-Realism-Mod-Client/assets/32923328/422c26b5-e027-432a-8cd8-f87c93c00af3)

**Comment by space-commits** [comment]
This is not an issue specific to Realism mod, please do not use the Issues section for general support.
